module.exports = {
    categories: [
        {
            id: 1,
            name: 'Building',
        },
        {
            id: 2,
            name: 'Painting',
        },
        {
            id: 3,
            name: 'Welding',
        },
        {
            id: 4,
            name: 'Plumbing',
        },
    ],
    products: [
        {
            id: 1,
            name: 'Cement',
            purchasedPrice: 380,
            purchasedUnit: 'kg',

            baseUnit: 'g',
            baseUnitValue: 1000,
            stock: 500000,
            reorderPoint: 5,
            isActive: true,
            categoryId: 1,
        },
        {
            id: 2,
            name: 'Asian Gold Brown',
            purchasedPrice: 120,
            purchasedUnit: 'tin',

            baseUnit: 'tin',
            baseUnitValue: 1,

            stock: 100,
            reorderPoint: 10,
            isActive: false,
            categoryId: 2,
        },
        {
            id: 3,
            name: '4 inch Nail',
            purchasedPrice: 200,
            purchasedUnit: 'box',

            baseUnit: 'piece',
            baseUnitValue: 100,

            stock: 1000,
            reorderPoint: 5,
            isActive: true,
            categoryId: 3,
        },
    ],
    prices: [
        {
            id: 1,
            productId: 1,
            amount: 400,
            taxValue: 12,
            quantity: 10,
            unit: 'kg',
        },
        {
            id: 2,
            productId: 1,
            amount: 10,
            taxValue: 0.0,
            quantity: 1,
            unit: 'kg',
        },
        {
            id: 3,
            productId: 2,
            amount: 122,
            quantity: 1,
            taxValue: 4,
            unit: 'tin',
        },
        {
            id: 4,
            productId: 3,
            amount: 200,
            quantity: 1,
            unit: 'box',
            taxValue: 8.9,
        },
        {
            id: 5,
            productId: 3,
            amount: 2,
            taxValue: 0.0,
            quantity: 1,
            unit: 'piece',
        },
        {
            id: 6,
            productId: 3,
            amount: 80,
            taxValue: 0.0,
            quantity: 50,
            unit: 'piece',
        },
    ],
    customers: [
        {
            id: 1,
            name: 'Snowin',
            phone: '9360294348',
            email: 'snowin@gmail.com',
            points: 100,
        },
        {
            id: 2,
            name: 'Mark',
            phone: '9361292348',
            points: 40,
        },
        {
            id: 3,
            name: 'Kevin',
            phone: '9460294348',
            email: 'kevin@gmail.com',
            aadhaar: '2249-3285-1294',
            points: 0,
        },
    ],
    orders: [
        {
            id: 1,
            // paymentMethod: 'UPI',
            isPaid: false,
            paidAt: '2024-05-27T20:37:06.711Z',
            totalPrice: 1792,
        },
        {
            id: 2,
            customerId: 3,
            paymentMethod: 'CASH',
            isPaid: true,
            paidAt: '2024-05-17T15:51:54.165Z',
            totalPrice: 169.34,
        },
    ],
    orderItems: [
        {
            id: 1,
            quantity: 4,
            priceId: 1,
            orderId: 1,
            productId: 1,
        },
        {
            id: 2,
            quantity: 1,
            priceId: 2,
            orderId: 2,
            productId: 2,
        },
        {
            id: 3,
            quantity: 2,
            priceId: 5,
            orderId: 2,
            productId: 3,
        },
    ],
    transactions: [
        {
            id: 1,
            transactionType: 'PURCHASE',
            quantity: 500,
            productId: 1,
        },
        {
            id: 2,
            transactionType: 'PURCHASE',
            quantity: 100,
            productId: 2,
        },
        {
            id: 3,
            transactionType: 'PURCHASE',
            quantity: 10,
            productId: 3,
        },
    ],
};
